### ISSUE TITLE
Value rounding problem with decimal step

### ISSUE THREAD

**Issue by vbarinov** [competentum/cg-slider#11]
The values of slider handles aren't rounding correctly.

E.g. with `step = 0.2`:
![image](https://user-images.githubusercontent.com/1442435/27132560-c19ff492-5128-11e7-845c-077cb17a9c86.png)

As @pilyugin suggested, it's probably worthy to use `+val.toFixed(10)` expression.

**Comment by pilyugin** [comment]
fixed in #12 
released in [v0.1.5](https://github.com/competentum/cg-slider/releases/tag/v0.1.5)
