### ISSUE TITLE
Support for aria-valuetext

### ISSUE THREAD

**Issue by vbarinov** [competentum/cg-slider#9]
Screen readers read `aria-valuenow` attribute, which is not informative.

https://www.w3.org/TR/wai-aria/states_and_properties#aria-valuetext
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-valuetext_attribute

We can provide optional label list and update `aria-valuetext` if necessary.

**Comment by pilyugin** [comment]
Implemented in #10
